### PR TITLE
Generate badges in pure Markdown format

### PR DESCRIPTION
**Pull request by valery1707**
Currently, this action generating a one-lined HTML version of badges, but used features of HTML (image with alt text inside link with title text) can be replaced with multi-lined pure Markdown.

Pros:
* Markdown looks clearly
* Markdown uses the fewer symbols
* Multi-lined format make `blame` more useful

### CODE REVIEW

**Comment by valery1707** [comment]
Difference from `one-lined HTML` format with `multi-lined pure Markdown` can be seed at https://gist.github.com/valery1707/02fa433f9ba64d6cca26d51f214b83dc

**Review by pemtajo — APPROVED** [review]
Thank you for your contribution. This is a more elegant solution than mine.

Exist is a small bug in this, it needs an extra `\n` for the markdown to work well. I don't know why, because I agree that your solution should work.

But I approved and I will make a small correction to that.

**Comment by valery1707** [comment]
Updated [tests/markdowns/no_changes_happy_day.md](https://github.com/pemtajo/badge-readme/blob/c296b3fa9a9eb3cdd02375def1071b8687bc4d6d/tests/markdowns/no_changes_happy_day.md) rendered correctly without extra `\n` - in which place its needed?

**Comment by pemtajo** [comment]
After the tag `<!--START_SECTION:badges-->`, if you use my [README](https://github.com/pemtajo/pemtajo/blob/main/README.md) as an example and remove the blank line, you will see that markdown will not be rendered correctly. 

It doesn't make sense, I agree with you that it should work.

**Comment by valery1707** [comment]
Got it, thanks for the explanation

**Pull request merged**
